export const  USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const  USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const  USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const SET_ROLE_REQUEST = "SET_ROLE_REQUEST";
export const SET_ROLE_SUCCESS = "SET_ROLE_SUCCESS";
export const SET_ROLE_FAIL = "SET_ROLE_FAIL";

export const GET_ROLE_REQUEST = "GET_ROLE_REQUEST";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAIL = "GET_ROLE_FAIL";

export const  ADD_ROLE_REQUEST = "ADD_ROLE_REQUEST";
export const  ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const  ADD_ROLE_FAIL = "ADD_ROLE_FAIL";

export const  CEO_REGISTRATION_REQUEST = "CEO_REGISTRATION_REQUEST";
export const  CEO_REGISTRATION_SUCCESS = "CEO_REGISTRATION_SUCCESS";
export const  CEO_REGISTRATION_FAIL = "CEO_REGISTRATION_FAIL";

export const INVITE_USER_REQUEST = "INVITE_USER_REQUEST";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_FAIL = "INVITE_USER_FAIL";